### ISSUE TITLE
ESLint fails with non-JSON config

### ISSUE THREAD

**Issue by markogresak** [expo/eslint-config-universe#16]
Example `.prettierrc`
```yaml
printWidth: 100
tabWidth: 2
singleQuote: true
jsxBracketSameLine: true
trailingComma: 'es5'
```

It's in `YAML` format, which is correct [according to the documentation](https://prettier.io/docs/en/configuration.html#basic-configuration). 
But if I use it, I get this error:

```
SyntaxError: Cannot read config file: [redacted]/node_modules/eslint-config-universe/shared/prettier.js
Error: Unexpected token a in JSON at position 1
Referenced from: [redacted]/node_modules/eslint-config-universe/default.js
Referenced from: [redacted]t/.eslintrc.js
    at JSON.parse (<anonymous>)
    at readPrettierConfig ([redacted]/node_modules/eslint-config-universe/shared/readPrettierConfig.js:21:19)
    at Object.<anonymous> ([redacted]/node_modules/eslint-config-universe/shared/prettier.js:15:35)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

**Comment by ide** [comment]
Thanks for the PR -- will take a look.
